# Generated by Django 5.1.6 on 2025-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtask',
            name='file',
        ),
        migrations.RemoveField(
            model_name='downloadtask',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='downloadtask',
            name='status',
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='download_url',
            field=models.URLField(blank=True, help_text='Public URL to the final ZIP stored in Supabase Storage', null=True),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the download task was created'),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='url',
            field=models.URLField(help_text='The Spotify URL requested by the user'),
        ),
    ]
