# Generated by Django 5.1.6 on 2025-05-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0002_remove_downloadtask_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='download_url',
            field=models.JSONField(blank=True, help_text='List of Supabase‐hosted ZIP URLs when the job completes', null=True),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='url',
            field=models.URLField(help_text='Original Spotify URL to download (track, album, or playlist)'),
        ),
        migrations.CreateModel(
            name='DownloadSong',
            fields=[
                ('id', models.CharField(help_text='Spotify track ID', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Song title/artist for display', max_length=255)),
                ('progress', models.IntegerField(default=0, help_text='Download progress for this song (0-100%)')),
                ('message', models.CharField(blank=True, help_text="Last status message (e.g. 'downloading', 'merged', 'error…')", max_length=255)),
                ('updated', models.DateTimeField(auto_now=True, help_text="When this song's record was last updated")),
                ('task', models.ForeignKey(help_text='The download job this song belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='spotdl_api.downloadtask')),
            ],
        ),
    ]
