# Generated by Django 5.1.6 on 2025-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0003_alter_downloadtask_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtask',
            name='download_url',
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='download_urls',
            field=models.JSONField(blank=True, help_text='List of Supabase-hosted ZIP URLs when the job completes', null=True),
        ),
    ]
