# Generated by Django 5.1.6 on 2025-05-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0004_remove_downloadtask_download_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadtask',
            old_name='download_urls',
            new_name='download_url',
        ),
    ]
