# Generated by Django 5.1.6 on 2025-05-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0005_rename_download_urls_downloadtask_download_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadtask',
            old_name='download_url',
            new_name='download_urls',
        ),
    ]
