# Generated by Django 5.1.6 on 2025-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0006_rename_download_url_downloadtask_download_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsong',
            name='sid',
            field=models.CharField(help_text='Spotify track ID', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='downloadsong',
            unique_together={('sid', 'task')},
        ),
    ]
