# Generated by Django 5.1.6 on 2025-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotdl_api', '0007_downloadsong_sid_alter_downloadsong_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='downloadsong',
            index=models.Index(fields=['sid', 'task'], name='spotdl_api__sid_bf3c72_idx'),
        ),
    ]
